### ISSUE TITLE
Parses html files as rdfxml

### ISSUE THREAD

**Issue by LaurensRietveld** [rdfjs/rdfxml-streaming-parser.js#13]
See the snippet below. When parsing with this parser we'd get 9 statements (mostly blank nodes). I'd expect an error though. 

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
        "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<body>
  <table>
    <tr>
      <td>some col 1</td>
      <td>some col 2</td>
      <td>some col 3</td>
    </tr>
   </table>
</body>
</html>
```

**Comment by rubensworks** [comment]
I don't think this should throw an error though (will double-check), as this is valid XML, just without any RDF triples.

In any case, no blank nodes should be emitted AFAICS, so something seems to be going wrong there.

**Comment by rubensworks** [comment]
I just went through the RDF/XML spec again, and as far as I can see, this should actually be valid RDF/XML. So the parser returns correct output here.

Concretely:
* `html` is the root, which is at the same time a [Typed Node Element](https://www.w3.org/TR/rdf-syntax-grammar/#section-Syntax-typed-nodes), which forms `_:b a <...html>`
* `body` is a [Property Element](https://www.w3.org/TR/rdf-syntax-grammar/#section-Syntax-node-property-elements), which forms `_:b1 <...body> _:b2`.
* `table` is a Typed Node Element
* `tr` is a Property Element
* ...

**Comment by LaurensRietveld** [comment]
Thanks for the check @rubensworks , you're right! I'll close this one
