### ISSUE TITLE
Parser is crashing on older RDF/XML based ontology

### ISSUE THREAD

**Issue by ktk** [rdfjs/rdfxml-streaming-parser.js#18]
We have an old RDF/XML based schema that is failing with the current parser. Pretty much every parser complains but some still convert it. The issue popped up [here](https://github.com/zazuko/rdf-vocabularies/issues/18#issuecomment-507575947), we did not agree yet if it should be able to parse this or not but it would be nice nevertheless ;)

It is this part: https://gist.github.com/vhf/23705814109f8c18cfb100c053f3dc6b#file-icaltzd-rdf-L705-L722

**Comment by rubensworks** [comment]
I remember finding the part of the RDF/XML spec a bit weird to enforce uniqueness of `rdf:ID`. I'll a config option to disable this behaviour, as I don't see a reason why this should be a hard crash.

**Comment by rubensworks** [comment]
Added in 1.3.0 via the `allowDuplicateRdfIds` option.
