### ISSUE TITLE
Invalid URI: at RdfXmlParser.newParseError

### ISSUE THREAD

**Issue by marcelomachado** [rdfjs/rdfxml-streaming-parser.js#22]
I am trying to parse the following RDF/XML file:

```
<?xml version="1.0" encoding="UTF-8" ?>
<rdf:RDF
xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
xmlns:owl="http://www.w3.org/2002/07/owl#"
xmlns:ub="http://swat.cse.lehigh.edu/onto/univ-bench.owl#">


<owl:Ontology rdf:about="">
<owl:imports rdf:resource="http://swat.cse.lehigh.edu/onto/univ-bench.owl" />
</owl:Ontology>
</rdf:RDF>

```
However the following error occurs:

```
Invalid URI: 
    at RdfXmlParser.newParseError (.../node_modules/rdfxml-streaming-parser/lib/RdfXmlParser.js:140:16)
```
It occurs because there is no IRI in `rdf:about` attribute, of `owl:Ontology` tag. I can't confirm if it's a valid rdf/xml file, however this one is from [LUBM benchmark](http://swat.cse.lehigh.edu/projects/lubm/index.htm) and `rdflib.js` can parse it.

**Comment by rubensworks** [comment]
Have you [configured](https://github.com/rdfjs/rdfxml-streaming-parser.js#configuration) a `baseIRI`?

**Comment by marcelomachado** [comment]
Indeed I forget it. Thanks!
