### ISSUE TITLE
Unable to parse geodata with CDATA

### ISSUE THREAD

**Issue by wouterbeek** [rdfjs/rdfxml-streaming-parser.js#52]
I'm unable to parse geospatial information, for example:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
  xmlns:geo="http://www.opengis.net/ont/geosparql#"
  xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
  xmlns:sf="http://www.opengis.net/ont/sf#">
  <sf:Point rdf:about="http://example.org/Geometry#PointA">
    <geo:asWKT rdf:datatype="http://www.opengis.net/ont/geosparql#wktLiteral"><![CDATA[<http://www.opengis.net/def/crs/EPSG/0/27700>
    POINT(60 60)]]></geo:asWKT>
  </sf:Point>
</rdf:RDF>
```

This may be related to the use of `CDATA` in general?

This is the corresponding output by rapper:
```
$ rapper test.rdf 
rapper: Parsing URI file:///home/wouter/tmp/test.rdf with parser rdfxml
rapper: Serializing with serializer ntriples
<http://example.org/Geometry#PointA> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.opengis.net/ont/sf#Point> .
<http://example.org/Geometry#PointA> <http://www.opengis.net/ont/geosparql#asWKT> "<http://www.opengis.net/def/crs/EPSG/0/27700>\n    POINT(60 60)"^^<http://www.opengis.net/ont/geosparql#wktLiteral> .
```

**Comment by rubensworks** [comment]
Hmm, I thought CDATA was already supported.
Is it giving an error? Or does it emit incorrect output?

**Comment by wouterbeek** [comment]
@rubensworks I do not have enough dev skills to run the parser in isolation, but when I upload the above RDF/XML snippet in TriplyDB I get a literal with empty lexical form and datatype IRI <http://www.opengis.net/ont/geosparql#wktLiteral>.

(The Turtle notation for the term would be `''^^geo:wktLiteral`.)

**Comment by rubensworks** [comment]
Just had a quick look, and apparently this lib doesn't handle CDATA yet. The underlying lib (sax) does emit it though, so implementing support should be quite simple.
