### ISSUE TITLE
Error "The prefix 'https' in term 'https:' was not bound" processing 'gist' vocab

### ISSUE THREAD

**Issue by pmcb55** [rdfjs/rdfxml-streaming-parser.js#55]
Hi, 

I'm seeing the error `The prefix 'https' in term 'https:' was not bound.` when parsing the 'gist' vocab at this URL: https://ontologies.semanticarts.com/o/gistCore11.0.0, whereas EasyRDF seems to parse it fine:
![image](https://user-images.githubusercontent.com/961445/170329224-d5f51f7c-9f83-49e8-9ef6-917793000763.png)

Can you re-produce this... (i.e., is the problem with the parser, the RDF, or how I'm using the parser!)?

Cheers,

Pat.

**Comment by pmcb55** [comment]
Seems like it was my mistake (I was unnecessarily forcing the Content-Type response from this namespace IRI to be RDF/XML - not sure why that caused the parser to blow up, but when I removed that it parsed fine!). Closing this now.

**Comment by rubensworks** [comment]
Glad to hear the problem is resolved :-)
