### ISSUE TITLE
Cannot parse unencoded URIs that have whitespaces

### ISSUE THREAD

**Issue by vgdaut** [rdfjs/rdfxml-streaming-parser.js#61]
URIs may contain unencoded symbols like whitespace, but IRI_REGEX seems to only accept encoded URIs. I got this error:
`ParseError: Invalid URI: https://www.gutenberg.org/files/56664/56664-h/Archive 2.zip`
This URI contains a whitespace instead of "+". I am wondering if there is a way to automatically encode all URIs before validating them?

**Comment by rubensworks** [comment]
Strictly, a whitespace is not allowed indeed.
But I'm definitely open to adding a parsing mode that disables URI validation.
